name: Build PDF

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            make
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: created-pdf
          path: ahmad_alhousseini.pdf
