name: Build LaTeX PDF

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            pdflatex Aahousseini_cv.tex
            pdflatex Aahousseini_cv.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: Aahousseini_cv.pdf
  upload_to_s3:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: cv-pdf
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload to S3
        run: |
          echo "📤 Uploading to S3..."
          aws s3 cp Aahousseini_cv.pdf s3://$AWS_S3_BUCKET
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
