name: Build LaTeX PDF

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            pdflatex Aahousseini_cv.tex
            pdflatex Aahousseini_cv.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: Aahousseini_cv.pdf
  upload_to_s3:
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: cv-pdf
      - name: Display structure of downloaded files
        run: ls -R
